name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-token:
    description: "The GITHUB_TOKEN secret"
    required: true
  pr-title:
    description: "Title of current Pull Request"
    required: true
runs:
  using: 'node16'
  main: dist/main/index.js
