on: 
  pull_request:
  
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: citrusj/pr-title-with-issue-number-action@v3.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pr-title: "${{ github.event.pull_request.title }}"
